# -*- coding: utf-8 -*-
"""CoCo_CNN_LSTM_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EANm9gNbBD7bydKD5l7VRozdS9zpy_jJ

# Image Captioning — CNN Encoder + LSTM Decoder sur COCO 2017

## Vue d'ensemble

Ce notebook implémente un système de **génération automatique de légendes d'images** (*image captioning*) entraîné sur **COCO 2017** (*Common Objects in Context*).

L'architecture suit le principe **Encoder → Decoder** (Show and Tell, Vinyals et al. 2015) :

```
Image RGB (224×224)
       │
       ▼
┌─────────────────────┐
│  CNN Encoder        │  ← CustomCNNBackbone (7 stages conv)
│  features visuelles │       Image → vecteur compact (512-dim)
└─────────────────────┘
       │  img_vec  [B, 512]
       ▼
┌─────────────────────┐
│  LSTM Decoder       │  ← CaptionLSTM (teacher forcing en train)
│  génère la légende  │       vecteur → séquence de mots
└─────────────────────┘
       │
       ▼
"a dog running in the park"
```

### Pourquoi COCO 2017 plutôt que Flickr8k ?

| Dataset | Images train | Captions/image | Benchmark |
|---------|-------------|----------------|-----------|
| Flickr8k | ~6 000 | 5 | Non standard |
| **COCO 2017** | **~118 000** | **5** | **Référence mondiale** |

COCO couvre **80 catégories d'objets** du quotidien et est 20× plus grand que Flickr8k.

## Étape 1 — Installation des dépendances

On s'assure d'avoir les bonnes versions de **PyTorch** et **TorchVision**.
`kagglehub` (pré-installé sur Colab) sera utilisé pour télécharger COCO 2017 automatiquement.
"""

# Mise à jour des librairies principales
# sympy est une dépendance interne de PyTorch
# À exécuter manuellement dans votre terminal : uv pip install --upgrade sympy torch torchvision
print("Installation terminee")

"""## Étape 2 — Imports

### Rôle de chaque librairie dans ce projet

| Import | Utilité |
|--------|---------|
| `os` | Manipulation des chemins (dossiers images, annotations) |
| `re` | Expressions régulières pour nettoyer le texte des captions |
| `random` | Sélection aléatoire d'une caption parmi les 5 disponibles par image |
| `json` | Lecture du fichier JSON COCO (`captions_train2017.json`) |
| `Counter` | Comptage des fréquences de mots pour construire le vocabulaire |
| `defaultdict` | Dictionnaire `{image → liste de captions}` sans initialisation manuelle |
| `torch`, `torch.nn` | Moteur de calcul, couches du réseau, autograd |
| `Dataset`, `DataLoader` | Abstraction du dataset et chargement par mini-batchs |
| `transforms` | Pipeline de transformation des images (resize, normalisation) |
| `PIL.Image` | Ouverture des fichiers JPEG de COCO |
| `matplotlib` | Visualisation des images et des captions prédites |

"""

import os
import re
import random
import json
from collections import Counter, defaultdict
import requests
from io import BytesIO
import urllib.request
import zipfile

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import matplotlib.pyplot as plt

print("Imports OK — PyTorch version :", torch.__version__)
print("GPU disponible :", torch.cuda.is_available())

"""## Étape 3 — Montage de Google Drive

On monte Drive **uniquement pour les checkpoints** (sauvegardes du modèle entre sessions).
COCO sera téléchargé via `kagglehub` dans le cache local de Colab.

> **Note** : Si Colab se déconnecte, le cache local est perdu mais les checkpoints Drive sont conservés. La session suivante re-téléchargera COCO (~5 min) mais reprendra l'entraînement depuis le dernier checkpoint sauvegardé.

"""

from google.colab import drive

# Monte Google Drive dans /content/drive/MyDrive/
drive.mount('/content/drive')
print("Google Drive monté")

"""## Étape 4 — Pré-traitement du texte : `basic_tokenize`

### Pourquoi tokeniser ?
Le LSTM travaille sur des **indices entiers**, pas du texte brut. Avant de construire le vocabulaire ou d'encoder une caption, il faut découper chaque phrase en une liste de **tokens (mots)** propres et standardisés.

### Pipeline appliqué aux captions COCO

Les captions COCO contiennent virgules, points, majuscules, doubles espaces...

```
"A man riding a horse, near the beach!"
  1. lower() + strip()
     → "a man riding a horse, near the beach!"
  2. re.sub(r"[^a-z0-9\s']", " ")   # supprime , . ! ? etc.
     → "a man riding a horse  near the beach "
  3. re.sub(r"\s+", " ")             # normalise les espaces
     → "a man riding a horse near the beach"
  4. split(" ")
     → ["a", "man", "riding", "a", "horse", "near", "the", "beach"]
```

"""

def basic_tokenize(s: str) -> list:
    # Étape 1 : tout en minuscules + suppression des espaces de début/fin
    # 'Dog' et 'dog' doivent être le même token dans le vocabulaire
    s = s.lower().strip()

    # Étape 2 : suppression de la ponctuation et des symboles spéciaux
    # On garde : lettres (a-z), chiffres (0-9), espaces et apostrophes (')
    # Tout le reste (!, ?, ., ,, ;, :...) est remplacé par un espace
    s = re.sub(r"[^a-z0-9\s']", " ", s)

    # Étape 3 : les remplacements précédents créent parfois des espaces multiples
    # On les écrase en un seul espace
    s = re.sub(r"\s+", " ", s)

    # Étape 4 : découpage de la phrase en liste de tokens
    return s.split(" ")


# ── Test rapide ────────────────────────────────────────────────────────────
test = "A man riding a horse, near the beach!"
print("Entrée :", test)
print("Sortie :", basic_tokenize(test))

"""## Étape 5 — Gestion du vocabulaire : classe `Vocab`

### Rôle général
La classe `Vocab` fait le **pont entre les mots et les indices entiers** que le modèle manipule.

| Méthode | Quand | Ce qu'elle fait |
|---------|-------|-----------------|
| `build(captions)` | 1 fois avant l'entraînement | Scanne toutes les captions COCO train → construit la table mot↔index |
| `encode(caption)` | Pendant l'entraînement | Texte → liste d'entiers (input du LSTM) |
| `decode(ids)` | Pendant l'évaluation | Liste d'entiers → texte lisible (output du LSTM) |

### Les 4 tokens spéciaux

| Token | Index | Rôle |
|-------|-------|------|
| `<pad>` | 0 | Rembourrage : aligne toutes les captions d'un batch à la même longueur |
| `<bos>` | 1 | *Begin Of Sequence* : signal de démarrage envoyé au LSTM |
| `<eos>` | 2 | *End Of Sequence* : le LSTM doit apprendre à prédire ce token pour terminer |
| `<unk>` | 3 | *Unknown* : remplace les mots absents du vocabulaire |

### `min_freq = 5` pour COCO
COCO contient ~600 000 captions. Sans filtre, le vocabulaire brut dépasse 30 000 mots (dont fautes de frappe, noms propres, hapax). Avec `min_freq=5`, on garde ~12 000–15 000 mots représentatifs : moins de paramètres, meilleure généralisation.

"""

class Vocab:
    # Vocabulaire du modele : gere la correspondance mots <-> indices entiers.
    # stoi : String TO Index  ex: {'dog': 57}
    # itos : Index TO String  ex: itos[57] == 'dog'

    def __init__(self, min_freq: int = 2):
        self.min_freq = min_freq  # mots vus < min_freq fois dans COCO → ignores
        self.stoi = {}            # dict  : mot   → index (pour encoder)
        self.itos = []            # liste : index → mot   (pour decoder)

        # Noms des 4 tokens speciaux (seront aux indices 0, 1, 2, 3)
        self.pad = '<pad>'   # Padding : aligne les sequences dans un batch
        self.bos = '<bos>'   # Begin Of Sequence : amorce le decodeur LSTM
        self.eos = '<eos>'   # End Of Sequence   : signal de fin a predire
        self.unk = '<unk>'   # Unknown           : substitut pour les mots rares

    def build(self, captions_list: list) -> None:
        # ── Comptage des frequences de chaque mot dans tout le corpus ──────
        # Pour COCO : ~590 000 captions, appelée UNE SEULE FOIS avant l'entrainement
        counter = Counter()
        for cap in captions_list:
            # basic_tokenize nettoie la caption avant de compter ses mots
            counter.update(basic_tokenize(cap))

        # ── Tokens speciaux : toujours aux indices 0 → 3 ──────────────────
        # Ainsi pad_id=0, bos_id=1, eos_id=2, unk_id=3 de facon garantie
        self.itos = [self.pad, self.bos, self.eos, self.unk]

        # ── Ajout des mots qui atteignent le seuil de frequence ───────────
        for word, count in counter.items():
            if count >= self.min_freq:
                self.itos.append(word)

        # ── Construction du dict inverse : mot → index ────────────────────
        self.stoi = {word: idx for idx, word in enumerate(self.itos)}

    def encode(self, caption: str, max_len: int = None) -> list:
        # Format de sortie : [<bos>, mot1, mot2, ..., motN, <eos>]
        # Les mots inconnus sont remplaces par l'index de <unk>

        # Encadre les tokens nettoyes avec les balises debut/fin
        tokens = [self.bos] + basic_tokenize(caption) + [self.eos]

        # Conversion mot → index (mots inconnus → index de <unk>)
        ids = [self.stoi.get(t, self.stoi[self.unk]) for t in tokens]

        # Troncature optionnelle (evite les sequences trop longues en memoire)
        if max_len is not None:
            ids = ids[:max_len]

        return ids

    def decode(self, ids: list) -> str:
        # Convertit une liste d'indices en phrase lisible
        # Utilisee pour lire les predictions du modele apres l'inference
        words = []
        for i in ids:
            # Recuperation du mot (ou <unk> si index hors bornes)
            w = self.itos[i] if 0 <= i < len(self.itos) else self.unk

            # Arret immediat des que le LSTM a predit la fin de sequence
            if w == self.eos:
                break

            # On ignore <bos> et <pad> dans la phrase affichee
            if w not in (self.bos, self.pad):
                words.append(w)

        return ' '.join(words)

"""## Étape 6 — Dataset COCO : classe `CocoCaptionDataset`

### Format des annotations COCO vs Flickr8k

**Flickr8k** utilisait un fichier texte CSV simple :
```
image_name.jpg,caption texte
```

**COCO 2017** utilise un fichier **JSON structuré** (`captions_train2017.json`) :
```json
{
  "images":      [{"id": 391895, "file_name": "000000391895.jpg"}, ...],
  "annotations": [{"image_id": 391895, "caption": "A man with a..."}, ...]
}
```
On construit d'abord le dict `image_id → file_name`, puis on associe chaque caption à son image.

### Stratégie de sélection des captions (5 par image)
- **Train** (`training=True`) : caption **aléatoire** parmi les 5 → varie à chaque epoch (augmentation de données textuelles).
- **Validation** (`training=False`) : **toujours la première** caption → loss reproductible.

"""

class CocoCaptionDataset(Dataset):
    # Dataset PyTorch qui télécharge les images à la volée via l'API pycocotools

    def __init__(self, coco, img_ids,
                 vocab, transform=None, max_len=40, training=True):
        self.coco       = coco          # Instance de pycocotools.coco.COCO
        self.img_ids    = img_ids       # Liste des IDs d'images
        self.vocab      = vocab         # vocabulaire pour encoder les captions
        self.transform  = transform     # pipeline torchvision
        self.max_len    = max_len       # troncature si caption > max_len tokens
        self.training   = training      # True=aleatoire, False=fixe (val)

    def __len__(self):
        # Nombre total d'images dans ce split
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id = self.img_ids[idx]

        # ── 1) Récupération de l'URL via l'API ────────────────────────────
        img_info = self.coco.loadImgs(img_id)[0]
        img_url  = img_info['coco_url']

        # ── 2) Téléchargement de l'image en RAM (Streaming) ───────────────
        try:
            response = requests.get(img_url, timeout=10)
            img = Image.open(BytesIO(response.content)).convert('RGB')
        except Exception as e:
            # Sécurité anti-crash si le lien est mort ou timeout
            img = Image.new('RGB', (224, 224), (0, 0, 0))

        # ── 3) Transformations : resize 224x224, ToTensor, Normalize ──────
        if self.transform:
            img = self.transform(img)   # → Tensor [3, 224, 224]

        # ── 4) Selection de la caption via l'API ──────────────────────────
        ann_ids = self.coco.getAnnIds(imgIds=img_id)
        anns = self.coco.loadAnns(ann_ids)
        cap_list = [ann['caption'] for ann in anns]

        if not cap_list:
            cap_list = [""]
            
        if self.training:
            # En train : caption differente a chaque epoch (diversite)
            cap = random.choice(cap_list)
        else:
            # En val : toujours la meme caption → resultats reproductibles
            cap = cap_list[0]

        # ── 5) Encodage de la caption en indices ──────────────────────────
        # Produit : [bos_id, id1, id2, ..., idN, eos_id]  (tronque a max_len)
        ids = self.vocab.encode(cap, max_len=self.max_len)

        return img, torch.tensor(ids, dtype=torch.long)

"""## Étape 7 — Assemblage des batchs : `make_collate_fn`

### Problème : longueurs variables dans un batch

Chaque caption COCO encodée a une longueur différente (5 à 40 tokens). Or PyTorch exige des tenseurs **rectangulaires**.

**Solution** : *padding dynamique* — on complète les captions courtes avec `<pad>` jusqu'à la longueur de la plus longue du batch.

```
Caption 1 : [1, 45, 12, 78,  2,  0,  0]   (paddée)
Caption 2 : [1, 23, 67, 89, 34, 12,  2]   (la plus longue)
Caption 3 : [1,  8, 42,  2,  0,  0,  0]   (paddée)
            └────── max_len du batch ──┘
```

### Pourquoi une factory `make_collate_fn(pad_id)` ?
Le `DataLoader` attend une `collate_fn(batch)` sans argument supplémentaire. La factory capture `pad_id` dans sa *closure* : la fonction retournée peut y accéder sans variable globale.

### Ce que retourne le batch
```
imgs    → Tensor [B, 3, 224, 224]  images normalisées
padded  → Tensor [B, T_max]        captions paddées (<pad> aux positions vides)
lengths → Tensor [B]               longueur réelle de chaque caption
```
`lengths` permet d'ignorer les `<pad>` dans le calcul de la loss.

"""

def make_collate_fn(pad_id: int):
    # Cree la fonction collate utilisee par le DataLoader.
    # Le padding est 'dynamique' : on complete jusqu'a la longueur de la
    # caption la plus longue DU BATCH (pas une valeur globale fixe).
    # → moins de memoire et de calculs gaspilles sur des tokens inutiles.

    def collate(batch):
        # batch : liste de tuples (img_tensor, cap_ids_tensor) du Dataset

        # Separe les images et les captions du batch
        imgs, caps = zip(*batch)

        # Empile les images en un seul tenseur [B, C, H, W]
        imgs = torch.stack(imgs, dim=0)

        # Longueur reelle de chaque caption (nb de tokens avant padding)
        lengths = torch.tensor([len(c) for c in caps], dtype=torch.long)

        # La longueur de padding = caption la plus longue du batch
        max_len = int(lengths.max().item())

        # Tenseur de sortie entierement rempli de pad_id
        # Les positions non ecrasees resteront <pad>
        padded = torch.full((len(caps), max_len), pad_id, dtype=torch.long)

        # Copie chaque caption dans ses positions reelles
        # Les positions restantes (len(c) → max_len) gardent pad_id
        for i, c in enumerate(caps):
            padded[i, :len(c)] = c

        return imgs, padded, lengths

    return collate

"""## Étape 8 — Encodeur CNN (1/3) : brique `ConvBlock`

### Rôle
`ConvBlock` est la **brique élémentaire** du backbone CNN. Il encapsule le triplet standard **Conv2d → BatchNorm2d → ReLU**, répété plusieurs fois pour construire l'encodeur visuel.

### Les 3 couches du bloc

| Couche | Rôle | Remarque |
|--------|------|----------|
| `Conv2d` | Détecte des patterns locaux (bords, textures, formes) | `bias=False` car BatchNorm annule le biais |
| `BatchNorm2d` | Normalise les activations → stabilise l'apprentissage | Réduit la sensibilité au LR |
| `ReLU` | Introduit la non-linéarité | `inplace=True` économise de la RAM |

### Paramètres configurables
- `k=3, s=1, p=1` → convolution **3×3** qui **conserve** la résolution spatiale
- `k=7, s=2, p=3` → convolution **7×7** avec **downsampling ×2** (utilisé dans le stem)
- `s=2` → **downsampling ×2** (résolution divisée par 2)

"""

class ConvBlock(nn.Module):
    # Brique convolutionnelle standard : Conv2d -> BatchNorm2d -> ReLU.
    # Peut servir a extraire des features (s=1) ou reduire la resolution (s=2).

    def __init__(self, in_ch, out_ch, k=3, s=1, p=1):
        super().__init__()

        # Convolution 2D : detecte des patterns locaux dans l'image
        # bias=False : le biais est inutile quand BatchNorm suit (elle le compense)
        self.conv = nn.Conv2d(in_ch, out_ch, k, stride=s, padding=p, bias=False)

        # Normalisation par batch : stabilise la distribution des activations
        # et accelere la convergence de l'entrainement
        self.bn = nn.BatchNorm2d(out_ch)

        # Activation ReLU : introduit la non-linearite indispensable au reseau
        # inplace=True modifie le tenseur directement pour economiser de la RAM
        self.act = nn.ReLU(inplace=True)

    def forward(self, x):
        # Pipeline sequentiel : Conv → BatchNorm → ReLU
        # Entree x : [B, in_ch, H, W]  →  Sortie : [B, out_ch, H', W']
        return self.act(self.bn(self.conv(x)))

"""## Étape 9 — Encodeur CNN (2/3) : `CustomCNNBackbone`

### Objectif
Transformer une image `[B, 3, 224, 224]` en un **vecteur compact** `[B, 512]` qui résume sémantiquement la scène.

### Architecture : 7 stages progressifs

```
Image  (3, 224, 224)
  ↓  stem  : Conv 7x7 s=2 + MaxPool s=2      →  (64,  56, 56)   resolution /4
  ↓  stage1 : 2x ConvBlock(64→64)            →  (64,  56, 56)   inchange
  ↓  stage2 : ConvBlock(64→128, s=2) + conv  →  (128, 28, 28)   resolution /2
  ↓  stage3 : ConvBlock(128→256, s=2) + conv →  (256, 14, 14)   resolution /2
  ↓  stage4 : ConvBlock(256→512, s=2) + conv →  (512,  7,  7)   resolution /2
  ↓  Global Average Pooling (mean H x W)     →  (512)
  ↓  Linear(512→512) + BN1d + ReLU           →  vecteur v (512)
```

**Résolution totale divisée par 32** : 224 / 32 = 7 pixels résiduels.

### Global Average Pooling vs Flatten
Au lieu de flattenner `(512, 7, 7)` → 25 088 valeurs, on prend la **moyenne spatiale** → 512 valeurs. Avantages : invariant à la taille d'entrée, bien moins de paramètres.

### Projection finale avec `BatchNorm1d`
La `BatchNorm1d` normalise le vecteur image avant son injection dans les couches `init_h` / `init_c` du LSTM, ce qui stabilise l'initialisation du décodeur.

"""

class CustomCNNBackbone(nn.Module):
    # Encodeur CNN personnalise : Image [B,3,H,W] -> Vecteur [B, d_embed]
    # Architecture inspiree de ResNet sans connexions residuelles.

    def __init__(self, d_embed=512, base=64):
        super().__init__()

        # ── Stem : premiere couche d'entree ───────────────────────────────
        # Conv 7x7 avec large champ receptif puis MaxPool
        # → resolution divisee par 4 en deux etapes
        self.stem = nn.Sequential(
            ConvBlock(3, base, k=7, s=2, p=3),     # (3,224,224) → (64,112,112)
            nn.MaxPool2d(3, stride=2, padding=1)    # (64,112,112) → (64,56,56)
        )

        # ── Stage 1 : extraction de features a resolution constante ───────
        # 2 blocs ConvBlock sans downsampling (stride=1 par defaut)
        self.stage1 = nn.Sequential(
            ConvBlock(base, base),      # (64,56,56) → (64,56,56)
            ConvBlock(base, base)       # (64,56,56) → (64,56,56)
        )

        # ── Stage 2 : downsampling x2 + doublement des canaux ────────────
        self.stage2 = nn.Sequential(
            ConvBlock(base, base*2, s=2),   # (64,56,56) → (128,28,28) stride=2
            ConvBlock(base*2, base*2)       # (128,28,28) → (128,28,28)
        )

        # ── Stage 3 : downsampling x2 + doublement des canaux ────────────
        self.stage3 = nn.Sequential(
            ConvBlock(base*2, base*4, s=2), # (128,28,28) → (256,14,14)
            ConvBlock(base*4, base*4)       # (256,14,14) → (256,14,14)
        )

        # ── Stage 4 : downsampling x2 + doublement des canaux ────────────
        self.stage4 = nn.Sequential(
            ConvBlock(base*4, base*8, s=2), # (256,14,14) → (512,7,7)
            ConvBlock(base*8, base*8)       # (512,7,7) → (512,7,7)
        )

        # ── Projection finale : carte de features → vecteur d'embedding ───
        # Linear : projette les 512 canaux vers d_embed dimensions
        # BatchNorm1d : normalise le vecteur pour stabiliser l'initialisation du LSTM
        # ReLU : non-linearite finale
        self.proj = nn.Sequential(
            nn.Linear(base*8, d_embed),
            nn.BatchNorm1d(d_embed),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        # Passage progressif dans les stages convolutionnels
        x = self.stem(x)    # [B, 64,  56, 56]
        x = self.stage1(x)  # [B, 64,  56, 56]
        x = self.stage2(x)  # [B, 128, 28, 28]
        x = self.stage3(x)  # [B, 256, 14, 14]
        x = self.stage4(x)  # [B, 512,  7,  7]

        # Global Average Pooling : moyenne sur les dimensions spatiales H et W
        # Resumer toute la carte de features en un unique vecteur par image
        x = x.mean(dim=(2, 3))   # [B, 512]

        # Projection lineaire + normalisation + activation → vecteur final
        v = self.proj(x)          # [B, d_embed]

        return v

"""## Étape 10 — Décodeur LSTM : `CaptionLSTM`

### Principe : le LSTM comme générateur conditionné par l'image

Le décodeur reçoit le **vecteur image** `img_vec` et génère la caption mot par mot. L'image conditionne le LSTM via ses **états initiaux** `(h0, c0)`.

### Teacher Forcing (entraînement)

On fournit au LSTM les **vrais mots** comme entrée à chaque pas :

```
Entrée  :  <bos>   a      man    riding    a    horse
LSTM    :   h1     h2      h3      h4      h5    h6
Cible   :    a    man    riding    a      horse  <eos>
```

### Greedy Decoding (inférence)
En inférence, le modèle prend son propre output comme input du pas suivant :

```
<bos> → LSTM → 'a' → LSTM → 'man' → LSTM → 'riding' → ... → <eos>
```

### Initialisation de (h0, c0) depuis l'image
Deux couches `Linear` projettent le vecteur image vers `h0` et `c0`. Cela **conditionne** le LSTM sur le contenu visuel dès le premier pas.

"""

class CaptionLSTM(nn.Module):
    # Decodeur LSTM : genere une caption a partir d'un vecteur image.
    # En entrainement : teacher forcing → logits [B, T, V]
    # En inference    : greedy decoding → tokens [B, T_gen]

    def __init__(self, vocab_size, d_embed=512, hidden=512,
                 num_layers=1, dropout=0.2, pad_id=0):
        super().__init__()
        self.hidden     = hidden
        self.num_layers = num_layers
        self.pad_id     = pad_id

        # Table d'embedding : convertit un index de mot en vecteur dense [D]
        # padding_idx : le vecteur de <pad> est maintenu a zero (non mis a jour)
        self.word_emb = nn.Embedding(vocab_size, d_embed, padding_idx=pad_id)

        # Dropout sur les embeddings : regularisation du decodeur
        self.drop = nn.Dropout(dropout)

        # Projections du vecteur image vers les etats initiaux du LSTM
        # Ces deux couches permettent a l'image de 'demarrer' le LSTM
        self.init_h = nn.Linear(d_embed, hidden * num_layers)  # img → h0
        self.init_c = nn.Linear(d_embed, hidden * num_layers)  # img → c0

        # LSTM : traite la sequence d'embeddings mots pas a pas
        # batch_first=True : tenseurs en [B, T, D] (plus intuitif)
        self.lstm = nn.LSTM(
            d_embed, hidden,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0  # dropout inter-couches si empile
        )

        # Couche de sortie : etat cache → scores sur tout le vocabulaire
        self.fc = nn.Linear(hidden, vocab_size)

    def _init_state(self, img_vec):
        # Calcule les etats initiaux (h0, c0) du LSTM depuis le vecteur image.
        # PyTorch LSTM attend les etats de forme [num_layers, B, hidden]
        B = img_vec.size(0)

        # Linear → tanh : projection dans [-1, 1] (meme plage que les etats LSTM)
        # view + transpose : reshape pour le format PyTorch LSTM
        h0 = (torch.tanh(self.init_h(img_vec))
                .view(B, self.num_layers, self.hidden)
                .transpose(0, 1)
                .contiguous())

        c0 = (torch.tanh(self.init_c(img_vec))
                .view(B, self.num_layers, self.hidden)
                .transpose(0, 1)
                .contiguous())

        return h0, c0

    def forward(self, img_vec, captions_in):
        # ── Passe forward en entrainement (teacher forcing) ────────────────
        # captions_in : tokens decales (sans <eos>) → [B, T]

        # Embedding + dropout sur la sequence d'entree entiere
        emb = self.drop(self.word_emb(captions_in))   # [B, T, D]

        # Initialisation des etats caches depuis le vecteur image
        h0, c0 = self._init_state(img_vec)

        # LSTM sur toute la sequence en un seul appel (teacher forcing)
        out, _ = self.lstm(emb, (h0, c0))             # [B, T, H]

        # Projection vers le vocabulaire : un vecteur de logits par position
        logits = self.fc(out)                          # [B, T, V]

        return logits

    @torch.no_grad()
    def generate_greedy(self, img_vec, bos_id, eos_id, max_len=30):
        # ── Generation en inference par greedy decoding ────────────────────
        # A chaque pas : on selectionne le mot avec le score le plus eleve (argmax).
        # Ce mot devient l'entree du pas suivant (decodage auto-regressif).

        B      = img_vec.size(0)
        device = img_vec.device

        # Initialisation de l'etat LSTM depuis l'image
        h, c = self._init_state(img_vec)

        # Amorcage avec le token <bos> pour chaque element du batch
        cur = torch.full((B, 1), bos_id, device=device, dtype=torch.long)

        out_tokens = []   # stocke les tokens generes a chaque pas

        # Masque pour detecter les sequences terminees (ont predit <eos>)
        finished = torch.zeros(B, device=device, dtype=torch.bool)

        for _ in range(max_len):
            # Embedding du dernier token predit uniquement (auto-regressif)
            emb = self.word_emb(cur[:, -1:])         # [B, 1, D]

            # Un seul pas LSTM : mise a jour de h et c
            o, (h, c) = self.lstm(emb, (h, c))

            # Logits → token avec le score maximum
            logits = self.fc(o[:, -1])               # [B, V]
            nxt    = torch.argmax(logits, dim=-1)    # [B]
            out_tokens.append(nxt)

            # Marque les sequences qui ont genere <eos>
            finished |= (nxt == eos_id)

            # Concatene le nouveau token a la sequence courante
            cur = torch.cat([cur, nxt.unsqueeze(1)], dim=1)

            # Arret anticipe si tous les elements du batch ont termine
            if finished.all():
                break

        # Retourne les tokens generes sous forme de tenseur [B, T_gen]
        return torch.stack(out_tokens, dim=1)

"""## Étape 11 — Modèle complet : `CaptionModel`

### Architecture CNN-LSTM (Show and Tell)

`CaptionModel` assemble l'encodeur et le décodeur dans un seul module PyTorch.

```
images [B, 3, 224, 224]
          |
          v  self.encoder  (CustomCNNBackbone)
    img_vec [B, 512]
          |
          v  self.decoder  (CaptionLSTM) + captions_in [B, T]
    logits [B, T, vocab_size]
          |
          v  CrossEntropyLoss vs targets [B, T]
         loss
```

En inférence : `model.decoder.generate_greedy(img_vec, bos_id, eos_id)`

"""

class CaptionModel(nn.Module):
    # Modele complet Image Captioning : CNN Encoder + LSTM Decoder.
    # Implementation du paradigme 'Show and Tell' (Vinyals et al., 2015).

    def __init__(self, vocab_size, d_embed=512, hidden=512, pad_id=0):
        super().__init__()

        # Encodeur visuel : Image → vecteur compact representant la scene
        self.encoder = CustomCNNBackbone(d_embed=d_embed, base=64)

        # Decodeur textuel : vecteur image → caption mot par mot
        self.decoder = CaptionLSTM(
            vocab_size, d_embed=d_embed, hidden=hidden, pad_id=pad_id
        )

    def forward(self, images, captions_in):
        # images      : [B, 3, H, W]  images normalisees
        # captions_in : [B, T]         tokens d'entree (sans le dernier token)

        # 1) Encodage : Image → vecteur de features visuelles
        img_vec = self.encoder(images)             # [B, d_embed]

        # 2) Decodage : vecteur + caption decalee → logits sur le vocabulaire
        return self.decoder(img_vec, captions_in)  # [B, T, V]

"""## Étape 12 — Boucle d'entraînement : `train_one_epoch`

### Teacher Forcing : décalage entrée / cible

Pour chaque caption `[<bos>, w1, w2, w3, <eos>]` :

| | Séquence |
|-|----------|
| **`captions_in`** `= tokens[:, :-1]` | `[<bos>, w1, w2, w3]` — entrée du LSTM |
| **`targets`** `= tokens[:, 1:]` | `[w1, w2, w3, <eos>]` — ce qu'il doit prédire |

À chaque position `t`, le modèle voit le mot `t` et doit prédire le mot `t+1`.

### Gradient Clipping
Les LSTM sont sujets à l'**explosion de gradients** lors de la rétropropagation à travers le temps. `clip_grad_norm_(..., 1.0)` plafonne la norme du gradient global à 1.0 avant la mise à jour des poids.

### `CrossEntropyLoss(ignore_index=pad_id)`
Les positions `<pad>` ne doivent pas contribuer à la loss. `ignore_index` masque automatiquement ces positions.

"""

def train_one_epoch(model, loader, optimizer, criterion, device, grad_clip=1.0):
    # Effectue un passage complet (1 epoch) sur le DataLoader d'entrainement.
    # Retourne la loss moyenne sur l'epoch.

    # Active le mode entrainement : dropout ON, BatchNorm utilise les stats du batch
    model.train()
    total_loss = 0.0

    for images, tokens, _lengths in loader:
        # Transfert sur le device (GPU si disponible)
        images = images.to(device)   # [B, 3, 224, 224]
        tokens = tokens.to(device)   # [B, T]

        # ── Teacher Forcing : decoupage entree / cible ────────────────────
        # captions_in : tout sauf le dernier token  → [<bos>, w1, w2, ..., wN]
        # targets     : tout sauf le premier token  → [w1, w2, ..., wN, <eos>]
        captions_in = tokens[:, :-1]   # [B, T-1]
        targets     = tokens[:,  1:]   # [B, T-1]

        # ── Forward pass ──────────────────────────────────────────────────
        # logits : [B, T-1, V]  scores bruts sur le vocabulaire
        logits = model(images, captions_in)

        # ── Calcul de la loss ─────────────────────────────────────────────
        # CrossEntropyLoss attend logits [N, V] et targets [N]
        # On aplatit les dimensions B et T → (B*(T-1), V) et (B*(T-1),)
        # Les positions <pad> sont ignorees automatiquement (ignore_index)
        loss = criterion(
            logits.reshape(-1, logits.size(-1)),   # [B*(T-1), V]
            targets.reshape(-1)                     # [B*(T-1)]
        )

        # ── Backward + mise a jour ────────────────────────────────────────
        optimizer.zero_grad()   # Remise a zero des gradients accumules

        loss.backward()         # Retropropagation : calcul des gradients

        # Gradient clipping : evite l'explosion des gradients dans le LSTM
        nn.utils.clip_grad_norm_(model.parameters(), grad_clip)

        optimizer.step()        # Mise a jour des poids

        total_loss += loss.item()

    # Loss moyenne sur tous les batchs de l'epoch
    return total_loss / max(1, len(loader))

"""## Étape 13 — Téléchargement et chargement de COCO 2017

### Format JSON COCO : deux sections séparées

**Flickr8k** : CSV simple `image.jpg,caption texte`

**COCO** : JSON avec deux listes distinctes :
```json
{
  "images": [
    {"id": 391895, "file_name": "000000391895.jpg"},
    ...
  ],
  "annotations": [
    {"image_id": 391895, "caption": "A man with a red helmet..."},
    ...
  ]
}
```
On doit construire un pont `image_id → file_name` pour associer annotations et images.

### `kagglehub` vs téléchargement manuel
- **Avant (Flickr8k)** : fichier ZIP depuis Drive, décompression manuelle.
- **Maintenant (COCO)** : une seule ligne `kagglehub.dataset_download(...)` télécharge et cache automatiquement dans `~/.cache/kagglehub/`. Les sessions suivantes utilisent le cache → instantané.

### Split 95% train / 5% val
COCO fournit un `val2017` officiel, mais nous n'utilisons que `train2017`. On fait un split manuel reproductible via `random.seed(42)`.

"""

from pycocotools.coco import COCO

# ── 1) Téléchargement des annotations uniquement (241 Mo) ───────────────
ann_file = "annotations/captions_train2017.json"
if not os.path.exists(ann_file):
    print("Téléchargement du fichier d'annotations COCO (241 Mo)...")
    os.makedirs("annotations", exist_ok=True)
    url = "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
    urllib.request.urlretrieve(url, "annotations.zip")
    print("Extraction en cours...")
    with zipfile.ZipFile("annotations.zip", 'r') as zip_ref:
        zip_ref.extractall(".")
    os.remove("annotations.zip")
    print("Annotations prêtes.")

# ── 2) Initialisation de l'API pycocotools ──────────────────────────────
print("Chargement des annotations avec pycocotools...")
coco = COCO(ann_file)

all_img_ids = list(coco.imgs.keys())
print(f"Images uniques trouvées : {len(all_img_ids):,}")

# ── 5) Split train / validation (95% / 5%) ───────────────────────────────
# random.seed garantit un split identique d'une session a l'autre
random.seed(42)
random.shuffle(all_img_ids)

split_idx   = int(len(all_img_ids) * 0.95)
train_ids   = all_img_ids[:split_idx]
val_ids     = all_img_ids[split_idx:]

print(f"Entrainement : {len(train_ids):,} images")
print(f"Validation   : {len(val_ids):,} images")

# ══════════════════════════════════════════════════════════════════════
# EXPLORATION DU DATASET COCO
# Affiche N images avec leurs 5 captions pour montrer la diversité
# des annotations humaines dans COCO
# ══════════════════════════════════════════════════════════════════════

def plot_coco_samples(n_images=4):
    """
    Affiche n_images images aléatoires du dataset COCO
    avec leurs captions humaines associées.
    """
    # Sélection aléatoire d'images parmi le split train
    random.seed(0)  # seed fixe pour reproductibilité
    picks = random.sample(train_ids, k=n_images)

    fig, axes = plt.subplots(1, n_images, figsize=(5 * n_images, 5))
    if n_images == 1:
        axes = [axes]

    for ax, img_id in zip(axes, picks):
        # Chargement de l'image originale via URL
        img_info = coco.loadImgs(img_id)[0]
        img_url  = img_info['coco_url']
        response = requests.get(img_url)
        img = Image.open(BytesIO(response.content)).convert('RGB')

        # Récupération des captions humaines associées
        ann_ids = coco.getAnnIds(imgIds=img_id)
        captions = [ann['caption'] for ann in coco.loadAnns(ann_ids)]

        # Affichage de l'image
        ax.imshow(img)
        ax.axis('off')
        ax.set_title(f"ID: {img_id}", fontsize=7, color='gray')

        # Affichage des captions sous l'image (jusqu'à 5)
        caption_text = "\n".join(
            [f"{i+1}. {c[:60]}{'...' if len(c) > 60 else ''}"
             for i, c in enumerate(captions[:5])]
        )
        ax.set_xlabel(caption_text, fontsize=8, labelpad=8,
                      ha='left', wrap=True)

    plt.suptitle(
        f"Exemples du dataset COCO 2017\n"
        f"{len(all_img_ids):,} images — ~5 captions humaines par image",
        fontsize=13, y=1.02
    )
    plt.tight_layout()
    plt.show()


plot_coco_samples(n_images=4)

"""## Étape 14 — Configuration, entraînement et sauvegarde

### Choix techniques

**Normalisation ImageNet** `mean=[0.485, 0.456, 0.406]`, `std=[0.229, 0.224, 0.225]` : même en entraînant from scratch, centre les pixels autour de 0 → gradients stables.

**AdamW** : variante d'Adam avec weight decay découplé, meilleure régularisation que l'Adam standard.

**ReduceLROnPlateau** : réduit le LR d'un facteur 0.5 si la `val_loss` ne s'améliore pas pendant `patience=2` epochs → convergence plus fine.

**Sauvegardes toutes les 1000 itérations** : COCO = ~3 700 batchs/epoch avec batch_size=32. Colab peut se déconnecter sans prévenir → on ne perd jamais plus de 1000 batchs de progression.

"""

# ── Choix du device ───────────────────────────────────────────────────────
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")
if device == "cuda":
    print(f"   GPU : {torch.cuda.get_device_name(0)}")

# ── 1) Construction du vocabulaire (captions TRAIN uniquement) ────────────
# On ne regarde jamais les captions de validation pour construire le vocab
# (evite la fuite d'information)
print("Extraction des captions d'entrainement via pycocotools...")
train_caps_all = []
for img_id in train_ids:
    ann_ids = coco.getAnnIds(imgIds=img_id)
    anns = coco.loadAnns(ann_ids)
    train_caps_all.extend([ann['caption'] for ann in anns])
print(f"Captions train : {len(train_caps_all):,}")

# min_freq=5 : les mots vus < 5 fois dans COCO deviennent <unk>
# Reduit le vocabulaire de ~30k a ~12-15k tokens sans perte significative
vocab = Vocab(min_freq=5)
vocab.build(train_caps_all)
print(f"Taille du vocabulaire : {len(vocab.itos):,} tokens")

# IDs des tokens speciaux (necessaires pour l'entrainement et l'inference)
pad_id = vocab.stoi[vocab.pad]   # = 0
bos_id = vocab.stoi[vocab.bos]   # = 1
eos_id = vocab.stoi[vocab.eos]   # = 2

# ── 2) Pipeline de transformations des images ─────────────────────────────
tfm = transforms.Compose([
    transforms.Resize((224, 224)),    # Toutes les images COCO → 224×224
    transforms.ToTensor(),            # PIL [0,255] → Tensor [0,1] en [C,H,W]
    transforms.Normalize(             # Normalisation ImageNet : centre les pixels
        mean=[0.485, 0.456, 0.406],
        std= [0.229, 0.224, 0.225]
    )
])

# ── 3) Datasets et DataLoaders ────────────────────────────────────────────
max_len = 40   # Coupe les captions > 40 tokens (couvre >99% de COCO)

# Dataset train : caption aleatoire parmi les 5 (diversite, augmentation)
train_ds = CocoCaptionDataset(
    coco, train_ids, vocab,
    transform=tfm, max_len=max_len, training=True
)
# Dataset val : toujours la premiere caption (reproductibilite de la loss)
val_ds = CocoCaptionDataset(
    coco, val_ids, vocab,
    transform=tfm, max_len=max_len, training=False
)

collate_fn = make_collate_fn(pad_id)

# batch_size=32 : bon compromis memoire/performance
# Reduire a 16 et num_workers a 0 si Colab signale une erreur de RAM
train_loader = DataLoader(
    train_ds, batch_size=32, shuffle=True,  num_workers=2, collate_fn=collate_fn
)
val_loader = DataLoader(
    val_ds,   batch_size=32, shuffle=False, num_workers=2, collate_fn=collate_fn
)
print(f"Batchs train : {len(train_loader):,} | Batchs val : {len(val_loader):,}")

# ── 4) Instanciation du modele ────────────────────────────────────────────
model = CaptionModel(
    vocab_size=len(vocab.itos),   # Taille reelle du vocabulaire
    d_embed=512,                  # Dimension partagee CNN ↔ LSTM
    hidden=512,                   # Taille de l'etat cache LSTM
    pad_id=pad_id
).to(device)

n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Parametres entrainables : {n_params:,}")

# ── 5) Loss, optimiseur et scheduler ─────────────────────────────────────
# ignore_index=pad_id : les positions <pad> ne contribuent pas a la loss
criterion = nn.CrossEntropyLoss(ignore_index=pad_id)

# AdamW : Adam avec weight decay decouple (meilleure regularisation)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-2)

# Reduit le LR x0.5 si val_loss stagne 2 epochs de suite
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=2
)

# ── 6) Reprise depuis un checkpoint (si disponible) ───────────────────────
ckpt_path   = "/content/drive/MyDrive/Deep learning/projet final/caption_model_coco_last.pt"
start_epoch = 1

if os.path.exists(ckpt_path):
    ckpt = torch.load(ckpt_path, map_location=device)
    model.load_state_dict(ckpt['model_state'])
    optimizer.load_state_dict(ckpt['optimizer_state'])
    if 'scheduler_state' in ckpt:
        scheduler.load_state_dict(ckpt['scheduler_state'])
    start_epoch = ckpt['epoch'] + 1
    print(f"Checkpoint trouve. Reprise a l epoch {start_epoch}")
else:
    print("Pas de checkpoint. Demarrage from scratch a l epoch 1.")

# ── 7) Fonction d'evaluation (validation loss) ───────────────────────────
@torch.no_grad()
def eval_epoch():
    # Calcule la loss moyenne sur le set de validation.
    # @torch.no_grad() : pas de calcul de gradients → plus rapide, moins de memoire
    model.eval()   # dropout OFF, BatchNorm utilise ses stats enregistrees
    total = 0.0
    for images, tokens, _ in val_loader:
        images = images.to(device)
        tokens = tokens.to(device)
        # Meme decoupage teacher forcing qu'en entrainement
        logits = model(images, tokens[:, :-1])
        loss   = criterion(
            logits.reshape(-1, logits.size(-1)),
            tokens[:, 1:].reshape(-1)
        )
        total += loss.item()
    return total / max(1, len(val_loader))

# ── 8) Boucle d'entrainement principale ──────────────────────────────────
epochs               = 20
save_every_n_batches = 1000   # Sauvegarde intermediaire anti-deconnexion Colab

print(f"Entrainement sur {epochs} epochs ({len(train_loader):,} batchs/epoch)")

for epoch in range(start_epoch, epochs + 1):
    model.train()   # Mode entrainement
    total = 0.0

    for batch_idx, (images, tokens, _) in enumerate(train_loader):
        images = images.to(device)
        tokens = tokens.to(device)

        # Forward : logits via teacher forcing
        logits = model(images, tokens[:, :-1])

        # Loss : CrossEntropy sur tous les tokens (sauf <pad>)
        loss = criterion(
            logits.reshape(-1, logits.size(-1)),
            tokens[:, 1:].reshape(-1)
        )

        # Backward : gradient + clipping + mise a jour
        optimizer.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)  # Anti-explosion LSTM
        optimizer.step()

        total += loss.item()

        # Sauvegarde de securite toutes les 1000 iterations
        if (batch_idx + 1) % save_every_n_batches == 0:
            print(f"  Epoch {epoch} | Batch {batch_idx+1}/{len(train_loader)} | Sauvegarde...")
            torch.save({
                'epoch':           epoch,
                'model_state':     model.state_dict(),
                'optimizer_state': optimizer.state_dict(),
                'vocab_itos':      vocab.itos,
                'pad_id':          pad_id,
                'bos_id':          bos_id,
                'eos_id':          eos_id,
            }, ckpt_path)

    # ── Fin d'epoch : metriques + scheduler + sauvegarde ─────────────────
    train_loss = total / max(1, len(train_loader))
    val_loss   = eval_epoch()
    current_lr = optimizer.param_groups[0]['lr']

    print(f"Epoch {epoch:02d}/{epochs} | train={train_loss:.4f} | val={val_loss:.4f} | lr={current_lr:.2e}")

    # Ajuste le LR si val_loss stagne
    scheduler.step(val_loss)

    # Sauvegarde complete en fin d'epoch (inclut l'etat du scheduler)
    torch.save({
        'epoch':           epoch,
        'model_state':     model.state_dict(),
        'optimizer_state': optimizer.state_dict(),
        'scheduler_state': scheduler.state_dict(),
        'vocab_itos':      vocab.itos,
        'pad_id':          pad_id,
        'bos_id':          bos_id,
        'eos_id':          eos_id,
    }, ckpt_path)
    print(f"  Checkpoint fin d epoch sauvegarde.")

# ── 9) Test rapide de generation apres entrainement ──────────────────────
model.eval()
images, tokens, _ = next(iter(val_loader))
images = images.to(device)

with torch.no_grad():
    img_vec = model.encoder(images)
    gen     = model.decoder.generate_greedy(
        img_vec, bos_id=bos_id, eos_id=eos_id, max_len=30
    )

print("Exemple predit :", vocab.decode(gen[0].tolist()))

# ── 10) Sauvegarde finale ─────────────────────────────────────────────────
ckpt_final = "/content/drive/MyDrive/Deep learning/projet final/caption_model_coco_final.pt"
torch.save({
    'model_state':     model.state_dict(),
    'vocab_itos':      vocab.itos,
    'pad_id':          pad_id,
    'bos_id':          bos_id,
    'eos_id':          eos_id,
    'scheduler_state': scheduler.state_dict(),
}, ckpt_final)
print(f"Sauvegarde finale : {ckpt_final}")

"""## Étape 15 — Inférence et visualisation

### Rechargement du modèle
Cette cellule peut être exécutée dans une **nouvelle session Colab** sans relancer l'entraînement. Elle recharge le vocabulaire et les poids depuis Drive.

### Comparaison GT / PRED
- **GT** (*Ground Truth*) : première caption humaine associée à l'image dans COCO.
- **PRED** : caption générée par le modèle via greedy decoding.

Avec CNN+LSTM de base (sans attention), les captions décrivent correctement le sujet principal mais peuvent manquer les relations entre plusieurs objets.

> Piste d'amélioration : ajouter un **mécanisme d'attention visuelle** sur les features spatiales avant le Global Average Pooling (Bahdanau attention).

"""

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")

# ── 1) Rechargement du checkpoint depuis Drive ────────────────────────────
ckpt_path = "checkpoints/caption_model_coco_last.pt"
print(f"Chargement : {ckpt_path}")
ckpt = torch.load(ckpt_path, map_location=device)
print(f"   Epoch sauvegardee : {ckpt.get('epoch', '?')}")

# ── 2) Reconstruction du vocabulaire depuis le checkpoint ─────────────────
# Le vocab est serialise comme une liste (plus leger que la classe entiere)
vocab      = Vocab()
vocab.itos  = ckpt['vocab_itos']
vocab.stoi  = {w: i for i, w in enumerate(vocab.itos)}  # reconstruction du dict inverse

pad_id = ckpt['pad_id']
bos_id = ckpt['bos_id']
eos_id = ckpt['eos_id']
print(f"Vocabulaire restaure : {len(vocab.itos):,} tokens")

# ── 3) Reconstruction du modele et chargement des poids ───────────────────
model = CaptionModel(
    vocab_size=len(vocab.itos), d_embed=512, hidden=512, pad_id=pad_id
).to(device)
model.load_state_dict(ckpt['model_state'])
model.eval()   # IMPORTANT : dropout OFF en inference
print("Modele charge en mode evaluation")

# ── 4) Pipeline de transformation (identique a l'entrainement !) ──────────
# On DOIT utiliser exactement les memes parametres qu'a l'entrainement
tfm = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# ── 5) Fonction de generation pour une image individuelle ─────────────────
@torch.no_grad()
def caption_one(img_url, max_len=30):
    # Télécharge l'image cible via son URL
    response = requests.get(img_url, timeout=10)
    img_pil = Image.open(BytesIO(response.content)).convert('RGB')

    # Applique les transformations + ajoute la dimension batch → [1, 3, 224, 224]
    x = tfm(img_pil).unsqueeze(0).to(device)

    # Encodage visuel : image → vecteur de features
    img_vec = model.encoder(x)

    # Generation de la caption par greedy decoding
    gen_ids = model.decoder.generate_greedy(
        img_vec, bos_id=bos_id, eos_id=eos_id, max_len=max_len
    )[0].tolist()

    # Decodage des indices en texte lisible
    pred = vocab.decode(gen_ids)

    return img_pil, pred

# ── 6) Affichage de N images aleatoires avec comparaison GT / PRED ────────
def show_random_tests(n=6):
    picks = random.sample(list(coco.imgs.keys()), k=min(n, len(coco.imgs)))   # n images aleatoires

    for img_id in picks:
        img_info = coco.loadImgs(img_id)[0]
        img_url  = img_info['coco_url']
        
        img_pil, pred = caption_one(img_url, max_len=30)

        # Premiere caption humaine comme reference de comparaison
        ann_ids = coco.getAnnIds(imgIds=img_id)
        anns = coco.loadAnns(ann_ids)
        gt = anns[0]['caption'] if anns else '(pas de ground truth)'

        # Affichage de l'image
        plt.figure(figsize=(7, 5))
        plt.imshow(img_pil)
        plt.axis('off')
        plt.title(f"ID: {img_id}", fontsize=8, color='gray')
        plt.tight_layout()
        plt.show()

        # Comparaison textuelle GT vs PRED
        print(f"  GT   (humain) : {gt}")
        print(f"  PRED (modele) : {pred}")
        print("-" * 65)

# Lancement sur 6 images COCO aleatoires
print("=" * 65)
print("GENERATION DE CAPTIONS — 6 IMAGES COCO ALEATOIRES")
print("=" * 65)
show_random_tests(n=6)